(()=>{"use strict";
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const KEY="TA_TJ_V4",state=JSON.parse(localStorage.getItem(KEY)||"null")||{lang:"ru",theme:"dark",progress:{},journal:[],plan:{},balance:10000,positions:[],score:0};
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const tr={ru:{home:"Главная",academy:"Академия",practice:"Практика",quiz:"Тест",progress:"Прогресс",about:"О проекте"},tj:{home:"Асосӣ",academy:"Академия",practice:"Таҷриба",quiz:"Тест",progress:"Пешрафт",about:"Дар бораи мо"}};
const courses=[
["01","Основы рынка","Forex, акции, крипто, котировки, Bid/Ask и спред.",6],
["02","Графики и свечи","OHLC, таймфреймы, импульс и чтение свечей.",8],
["03","Тренд и структура","HH, HL, LH, LL, уровни и рыночная структура.",8],
["04","Технический анализ","Support/Resistance, паттерны и confluence.",8],
["05","Risk Management","Размер позиции, Stop Loss, R:R и лимиты риска.",8],
["06","Торговая стратегия","Правила входа, выхода, фильтры и статистика.",8],
["07","Психология","Дисциплина, FOMO, revenge trading и журнал.",7],
["08","План трейдера","Система, review, статистика и подготовка.",7]];
const quiz=[
["Что означает Stop Loss?",["Лимит убытка","Гарантия прибыли","Комиссия","Спред"],0],
["Что такое риск 1%?",["1% капитала под риском","1% прибыли","1% комиссии","1% рынка"],0],
["Что показывает свеча?",["OHLC за период","Только открытие","Только объём","Только спред"],0],
["Что такое R:R?",["Соотношение риск/потенциальная прибыль","Размер счёта","Спред","Комиссия"],0],
["Зачем нужен журнал?",["Анализировать решения и статистику","Предсказывать новости","Выводить деньги","Менять брокера"],0],
["Что такое FOMO?",["Страх упустить движение","Тип ордера","Индикатор","Комиссия"],0],
["Что делает диверсификация?",["Распределяет риск","Гарантирует доход","Убирает стоп","Увеличивает кредит"],0],
["Что такое спред?",["Разница Bid/Ask","Размер депозита","Стоп","Свеча"],0],
["Что такое тренд?",["Направленное движение рынка","Комиссия","Размер позиции","Новость"],0],
["Почему демо полезен?",["Тренировка без реального капитала","Гарантия прибыли","Удаление риска","Замена обучения"],0]];
let qi=0,qs=0,activeSymbol="EUR/USD",data=[];
function makeData(n=60){let p=1.0842,a=[];for(let i=0;i<n;i++){let o=p,c=o+(Math.random()-.46)*.004,h=Math.max(o,c)+Math.random()*.002,l=Math.min(o,c)-Math.random()*.002;a.push({o,c,h,l});p=c}return a}
data=makeData();
function toast(m){let x=$("#toast");if(!x){x=document.createElement("div");x.id="toast";document.body.appendChild(x)}x.textContent=m;x.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>x.classList.remove("show"),2200)}
function navigate(id){let s=$("#"+id);if(!s)return;$$("main>section").forEach(x=>x.classList.remove("active"));s.classList.add("active");$$("[data-route]").forEach(x=>x.classList.toggle("active",x.dataset.route===id));$("#mobileMenu")?.classList.remove("open");scrollTo({top:0,behavior:"smooth"});if(id==="quiz")renderQuiz();if(id==="journal")renderJournal();if(id==="plan")loadPlan();if(id==="progress")renderProgress()}
function initNavigation(){document.addEventListener("click",e=>{let b=e.target.closest("[data-route]");if(b){e.preventDefault();navigate(b.dataset.route)}});$("#mobileMenuButton")?.addEventListener("click",()=>$("#mobileMenu")?.classList.toggle("open"));$("#menuBtn")?.addEventListener("click",()=>$("#mobileMenu")?.classList.toggle("open"));$("#languageToggle")?.addEventListener("click",toggleLanguage);$("#themeToggle")?.addEventListener("click",toggleTheme);$("#mobileLanguageToggle")?.addEventListener("click",toggleLanguage);$("#mobileThemeToggle")?.addEventListener("click",toggleTheme)}
function toggleLanguage(){state.lang=state.lang==="ru"?"tj":"ru";save();applyLanguage();toast(state.lang==="ru"?"Русский":"Тоҷикӣ")}
function applyLanguage(){let l=tr[state.lang]||tr.ru;document.documentElement.lang=state.lang;$$("[data-i18n]").forEach(e=>{let k=e.dataset.i18n;if(l[k])e.textContent=l[k]});if($("#currentLanguage"))$("#currentLanguage").textContent=state.lang==="ru"?"TJ":"RU";if($("#languageToggle"))$("#languageToggle").textContent=state.lang==="ru"?"TJ":"RU";renderCourses();renderProgress()}
function toggleTheme(){state.theme=state.theme==="dark"?"light":"dark";save();applyTheme();drawAll()}
function applyTheme(){document.documentElement.dataset.theme=state.theme;document.body.classList.toggle("light",state.theme==="light");if($("#themeIcon"))$("#themeIcon").textContent=state.theme==="dark"?"☾":"☀";if($("#themeToggle"))$("#themeToggle").textContent=state.theme==="dark"?"☾":"☀"}
function renderCourses(){let boxes=[$("#featuredCourses"),$("#courseGrid")].filter(Boolean);boxes.forEach(box=>box.innerHTML=courses.map(c=>{let done=Math.min(c[3],+state.progress[c[0]]||0),pct=Math.round(done/c[3]*100);return `<article class="course"><span class="num">MODULE ${c[0]}</span><h3>${c[1]}</h3><p>${c[2]}</p><div class="bar"><i style="width:${pct}%"></i></div><small>${done}/${c[3]} · ${pct}%</small><br><button data-course="${c[0]}">Открыть модуль →</button></article>`}).join(""));$$("[data-course]").forEach(b=>b.onclick=()=>{let id=b.dataset.course,c=courses.find(x=>x[0]===id);state.progress[id]=Math.min(c[3],(+state.progress[id]||0)+1);save();renderCourses();renderProgress();toast("Урок отмечен ✓")})}
function renderProgress(){let total=courses.reduce((a,c)=>a+c[3],0),done=courses.reduce((a,c)=>a+(+state.progress[c[0]]||0),0),pct=Math.round(done/total*100);let g=$(".progress-grid");if(g)g.innerHTML=[["Уроки",done+"/"+total],["Прогресс",pct+"%"],["Quiz",state.score],["Level",done>=40?"Advanced":done>=20?"Intermediate":"Beginner"]].map(x=>`<div class="stat-card"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join("");let a=$(".achievement-grid");if(a)a.innerHTML=[["🌱","Старт",done>=1],["📚","5 уроков",done>=5],["🔥","10 уроков",done>=10],["🧠","25 уроков",done>=25],["🏆","50 уроков",done>=50],["🎯","100%",pct>=100]].map(x=>`<div class="achievement-card ${x[2]?"unlocked":"locked"}"><div class="achievement-icon">${x[0]}</div><strong>${x[1]}</strong></div>`).join("")}
function drawChart(c){if(!c)return;let r=c.getBoundingClientRect(),d=devicePixelRatio||1,w=Math.max(280,r.width),h=Math.max(180,r.height);c.width=w*d;c.height=h*d;let x=c.getContext("2d");x.scale(d,d);x.clearRect(0,0,w,h);x.strokeStyle="rgba(255,255,255,.06)";for(let i=1;i<6;i++){x.beginPath();x.moveTo(0,i*h/6);x.lineTo(w,i*h/6);x.stroke()}let mn=Math.min(...data.map(v=>v.l)),mx=Math.max(...data.map(v=>v.h)),rg=mx-mn||1,cw=w/data.length*.7,py=v=>h-(v-mn)/rg*(h-20)-10;data.forEach((v,i)=>{let xx=i*w/data.length+w/data.length*.15,up=v.c>=v.o;x.strokeStyle=up?"#2ee59d":"#ff5f6d";x.fillStyle=x.strokeStyle;x.beginPath();x.moveTo(xx+cw/2,py(v.h));x.lineTo(xx+cw/2,py(v.l));x.stroke();let top=py(Math.max(v.o,v.c)),bot=py(Math.min(v.o,v.c));x.fillRect(xx,top,Math.max(2,cw),Math.max(2,bot-top))})}
function drawAll(){drawChart($("#heroChart"));drawChart($("#heroCanvas"));drawChart($("#mainCanvas"))}
function market(){let last=data.at(-1).c,ch=(last-1.08)/1.08*100;["#heroPrice","#marketPrice"].forEach(s=>$(s)&&( $(s).textContent=last.toFixed(5)));["#heroChange","#marketChange"].forEach(s=>$(s)&&($(s).textContent=(ch>=0?"+":"")+ch.toFixed(2)+"%"));drawAll()}
function initMarket(){setInterval(()=>{let p=data.at(-1).c,o=p,c=o+(Math.random()-.46)*.004;data.push({o,c,h:Math.max(o,c)+Math.random()*.002,l:Math.min(o,c)-Math.random()*.002});data.shift();market()},2500);addEventListener("resize",drawAll)}
function openPosition(side){let p=+($("#marketPrice")?.textContent||1.0842),size=+($("#orderSize")?.value||.1);state.positions.push({id:Date.now(),symbol:activeSymbol,side,size,entry:p});save();renderPositions();toast(side+" position opened")}
function renderPositions(){let box=$("#positions");if(!box)return;box.innerHTML=state.positions.length?state.positions.map(p=>`<div class="position-row"><span><b>${p.symbol}</b><br>${p.side}</span><span>Size<br>${p.size}</span><span>Entry<br>${p.entry}</span><span>P/L<br>—</span><button data-close="${p.id}">×</button></div>`).join(""):"<p class='muted'>No open positions.</p>";$$("[data-close]").forEach(b=>b.onclick=()=>{state.positions=state.positions.filter(p=>p.id!=b.dataset.close);save();renderPositions()});if($("#balance"))$("#balance").textContent="$"+state.balance.toLocaleString("en-US",{minimumFractionDigits:2})}
function initTerminal(){let sy=$("#symbols");if(sy){sy.innerHTML=["EUR/USD","GBP/USD","USD/JPY","XAU/USD","BTC/USD"].map(x=>`<button class="${x===activeSymbol?"selected":""}">${x}</button>`).join("");$$("button",sy).forEach(b=>b.onclick=()=>{$$("button",sy).forEach(x=>x.classList.remove("selected"));b.classList.add("selected");activeSymbol=b.textContent;toast(activeSymbol)})}$("#buyBtn")?.addEventListener("click",()=>openPosition("BUY"));$("#sellBtn")?.addEventListener("click",()=>openPosition("SELL"));renderPositions()}
function calcRisk(){let b=+$("#riskBalance")?.value||0,rp=+$("#riskPct")?.value||0,e=+$("#riskEntry")?.value||0,s=+$("#riskStop")?.value||0,t=+$("#riskTarget")?.value||0,r=b*rp/100,d=Math.abs(e-s),reward=Math.abs(t-e),rr=d?reward/d:0,box=$("#riskResult");if(box)box.innerHTML=[["Risk",r.toFixed(2)+" $"],["Stop",d.toFixed(5)],["Target",reward.toFixed(5)],["R:R",rr.toFixed(2)+" : 1"]].map(x=>`<div><span>${x[0]}</span><b>${x[1]}</b></div>`).join("")}
function initRisk(){$("#calcRisk")?.addEventListener("click",calcRisk);calcRisk()}
function initJournal(){$("#journalForm")?.addEventListener("submit",e=>{e.preventDefault();state.journal.unshift({symbol:$("#jSymbol").value,side:$("#jSide").value,entry:+$("#jEntry").value,exit:+$("#jExit").value,result:+$("#jResult").value,note:$("#jNote").value});save();e.target.reset();renderJournal();toast("Сделка сохранена ✓")});renderJournal()}
function renderJournal(){let b=$("#journalList");if(!b)return;b.innerHTML=state.journal.length?state.journal.map((x,i)=>`<div class="journal-row"><span><b>${x.symbol}</b><br>${x.side}</span><span>${x.entry}</span><span>${x.exit}</span><span>${x.result}$</span><button data-del="${i}">×</button></div>`).join(""):"<p class='muted'>Журнал пока пуст.</p>";$$("[data-del]").forEach(x=>x.onclick=()=>{state.journal.splice(+x.dataset.del,1);save();renderJournal()})}
function initPlan(){let f=$("#planForm");if(!f)return;f.addEventListener("submit",e=>{e.preventDefault();state.plan={strategy:$("#planStrategy")?.value,session:$("#planSession")?.value,risk:$("#planRisk")?.value,entry:$("#planEntry")?.value,exit:$("#planExit")?.value,psychology:$("#planPsychology")?.value};save();toast("План сохранён ✓")});loadPlan()}
function loadPlan(){let p=state.plan;["Strategy","Session","Risk","Entry","Exit","Psychology"].forEach(k=>{let x=$("#plan"+k);if(x)x.value=p[k.toLowerCase()]||""})}
function renderQuiz(){let b=$(".quiz-shell");if(!b)return;let q=quiz[qi];b.innerHTML=`<div class="quiz-progress"><b>${qi+1} / ${quiz.length}</b></div><h3>${q[0]}</h3><div class="quiz-options">${q[1].map((a,i)=>`<button data-answer="${i}">${String.fromCharCode(65+i)}. ${a}</button>`).join("")}</div><button id="nextQuiz" class="btn btn-primary" disabled>${qi===quiz.length-1?"Завершить":"Следующий →"}</button>`;let done=false;$$(".quiz-option").forEach(x=>x.onclick=()=>{if(done)return;done=true;let a=+x.dataset.answer;$$(".quiz-option").forEach((z,i)=>{z.disabled=true;if(i===q[2])z.classList.add("correct")});if(a===q[2])qs++;else x.classList.add("incorrect");$("#nextQuiz").disabled=false});$("#nextQuiz").onclick=()=>{if(qi===quiz.length-1){state.score=Math.max(state.score,qs);save();b.innerHTML=`<h2>🏆 ${qs}/${quiz.length}</h2><button id="restartQuiz" class="btn btn-primary">Пройти заново</button>`;$("#restartQuiz").onclick=()=>{qi=0;qs=0;renderQuiz()}}else{qi++;renderQuiz()}}}
function init(){try{applyTheme();applyLanguage();initNavigation();initTerminal();initRisk();initJournal();initPlan();renderQuiz();market();initMarket();$("#currentYear")&&($("#currentYear").textContent=new Date().getFullYear());setTimeout(drawAll,100);console.log("TRADE ACADEMY TJ initialized")}catch(e){console.error(e);toast("Interface loaded with safe mode")}}
document.readyState==="loading"?addEventListener("DOMContentLoaded",init):init();
})();